### ISSUE TITLE
I am against allowing paid softwares to be included in the recommend list.

### ISSUE THREAD

**Issue by zyppe** [cargo-youth/ToolDiy#21]
Paid softwares in the recommend list are just advertiment. This should not be allowed to add to this project.

**Comment by zyppe** [comment]
If this software or service can be used only when be paid, this should not be recommend.

**Comment by SakurajimaMaii** [comment]
We have received your comments and we will discuss them.

**Comment by Flurry-L** [comment]
> If this software or service can be used only when be paid, this should not be recommend.

**Comment by cargo-youth** [comment]
thanks，I think it is possible to share paid software and make information public. The original intention of this project is not for advertising and we will not have any advertising behavior

**Comment by cargo-youth** [comment]
ok，if there is no problem, close the issue

**Comment by zyppe** [comment]
> If this software or service can be used only when be paid, this should not be recommend.

If this software or service can be used only when be paid, this is mean that this software or service have been famous enouge so that it doesn't need to provide free version or sold it itself. Such as Windows, AWS, Typora, these are all famous enouge.

**Comment by cargo-youth** [comment]
However, there are many good paid software that you don't know about, so why label them as not recommended?

**Comment by zyppe** [comment]
To avoid recommending paid software to be as advertisement, "收费"/"Paid software" should be mentioned in the title of every paid software document.

**Comment by cargo-youth** [comment]
yes，we will consider  it

**Comment by cargo-youth** [comment]
so，i close this issue

**Comment by zyppe** [comment]
This question still not to be solved. This question should not be closed like openHarmony Community.

**Comment by cargo-youth** [comment]
In this submission fb2920263192e51db6748f6f8f5fc8e07894466d we have given some solutions, we will not change the appeal plan in the near future, so if there is no problem, I will close this issue
