### ISSUE TITLE
关于提升阅读体验

### ISSUE THREAD

**Issue by Flurry-L** [cargo-youth/ToolDiy#23]
1. 将默认 README 改为中文或许会观感更好（另一方面，目前中文版 README 更详细写了如何 PR，英文版还没同步）。
2. 建议在“如何贡献”中添加：尽量遵循[中英混排规范](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md)。
3. 可以增加 `template.md` 和 `template.en.md`，以提醒大家更醒目标注一些标签信息（如：可使用平台、是否收费）、优缺点、适用场景、备注。
4. 建议在 README 中添加：如果修改了原有目录结构请询问管理员。因为如果不修复 discussion 名可能会丢失原有评论。

**Comment by SakurajimaMaii** [comment]
默认的README已经被修改为中文😃

**Comment by SakurajimaMaii** [comment]
所有问题均已解决
