### ISSUE TITLE
Feature Request: 建议自动生成导航

### ISSUE THREAD

**Issue by pluveto** [cargo-youth/ToolDiy#48]
发现导航菜单需要手动生成。比较麻烦。
- [x] 可以做一个 Action，或者看看有没有已有的 Action，在 Build 前生成菜单

**Comment by SakurajimaMaii** [comment]
感谢你的议题！关于该事项，在 [#34 目录导航改为自动生成](https://github.com/cargo-youth/ToolDiy/issues/34) 已经被提及，我们进行了测试，但自动生成的目录似乎和所需要的有所不同，参考下图
- 手动
![image](https://user-images.githubusercontent.com/46998172/216832901-f0ba1d51-608a-472c-883b-e6680461ec00.png)
- 自动
![2A35733B1F8BE4B73C0548E161C9EF96](https://user-images.githubusercontent.com/46998172/216832853-44b1b24a-8e1a-4ab9-9b42-49d97aef8628.jpg)
不过因为你提及了 **Action** ，我们会在近期去查找是否有可行的方案

**Comment by pluveto** [comment]
如果你是指显示上会出现 `[^1]` 的话，可以考虑：
1. 使用替换的 Action 或者 Bash 脚本进行内容替换
2. 写一个脚本实现生成。从原理来说并不难。

**Comment by SakurajimaMaii** [comment]
不是，我指的是顺序和层级关系不对应，自动生成有两种顺序：
1. 默认先生成md文档，然后再生成文件夹，顺序为 index ， pr ， template ， markdown文件夹
2. 通过插件设置排序，此时按照规范下面的内容，生成的顺序则会变成 markdown 文件夹， index ， pr 和 template
但这两种排序显然都不符合要求（在上一个回复中手动截图提供的层级顺序），因而我并未采取。
(◦˙▽˙◦)当然如果你有更好的想法，也欢迎提出适合的方案。

**Comment by pluveto** [comment]
> 不是，我指的是顺序和层级关系不对应，自动生成有两种顺序：
> 
> 1. 默认先生成md文档，然后再生成文件夹，顺序为 index ， pr ， template ， markdown文件夹
> 2. 通过插件设置排序，此时按照规范下面的内容，生成的顺序则会变成 markdown 文件夹， index ， pr 和 template
> 
> 但这两种排序显然都不符合要求（在上一个回复中手动截图提供的层级顺序），因而我并未采取。 (◦˙▽˙◦)当然如果你有更好的想法，也欢迎提出适合的方案。

一般来说，可以通过 Markdown 内的元数据指定顺序。通常会提供 `priority` 或者 `order` 之类的字段。至少可以依据这个字段进行排序。或者，通过设置 `slug` 前缀影响顺序，例如 `01_xxx.md`

**Comment by SakurajimaMaii** [comment]
> > 不是，我指的是顺序和层级关系不对应，自动生成有两种顺序：
> > 
> > 1. 默认先生成md文档，然后再生成文件夹，顺序为 index ， pr ， template ， markdown文件夹
> > 2. 通过插件设置排序，此时按照规范下面的内容，生成的顺序则会变成 markdown 文件夹， index ， pr 和 template
> > 
> > 但这两种排序显然都不符合要求（在上一个回复中手动截图提供的层级顺序），因而我并未采取。 (◦˙▽˙◦)当然如果你有更好的想法，也欢迎提出适合的方案。
> 
> 一般来说，可以通过 Markdown 内的元数据指定顺序。通常会提供 `priority` 或者 `order` 之类的字段。至少可以依据这个字段进行排序。或者，通过设置 `slug` 前缀影响顺序，例如 `01_xxx.md`

哈哈， `01_xxx.md` 这个方案我也想过，但并未测试，稍后我会进行测试。

**Comment by SakurajimaMaii** [comment]
目前目录已经可以自动生成
