### ISSUE TITLE
社区 pull request 规范相关问题

### ISSUE THREAD

**Issue by jackyliu16** [cargo-youth/ToolDiy#59]
个人建议可以在 pull request 规范中添加新的规范类型 `docs` 专门用于文档上传者的提交，否则在对于本仓库可能需要进行的回溯过程中可能出现不影响网站主体内容更新的文档提交影响了在可能影响网站主体内容更新的 `feat` 中寻找问题时的效率。

**Comment by SakurajimaMaii** [comment]
该问题还未解决，会尽快安排更新
